sudo: false
language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
